### ISSUE TITLE
Using With Maven

### ISSUE THREAD

**Issue by laxatives** [pluradj/titan-attribute-serializer#1]
Is there a simple way to install this with maven? The instructions provided help get this started on a local machine, but I'd like to pull this serializer into deployed services.

**Comment by pluradj** [comment]
Thanks for the comment! This repo is intended as a coding example, not as a reusable asset. I'd recommend copying the code into your own application so that you can customize it for your own serialization needs.

**Comment by laxatives** [comment]
Quick question: I needed to make an additional Serializer for ArrayList, but its more or less identical to the other deseriazliers. Is it absolutely necessary to write the additional class? Do I need all/any of these custom serializers? It seems like the only configuration is casting the resulting object as the appropriate class.

**Comment by pluradj** [comment]
I'm not familiar with your graph model at all, but if the types in the ArrayList are all the same, perhaps you could just get away with using an array of objects instead. Also if you elevate your HashMap entries to vertex properties, you could avoid having to register a custom serializer for HashMap.
